apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: automatemail
  POSTGRES_USER: ayoub
  # Important for ebs volume, if not the pod will crash
  # The data directory is different than mount directory
  PGDATA: /var/lib/postgresql/data/pgdata

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-password
type: Opaque
data:
  db-password: YXlvdWI=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbcreation-script-configmap
data:
  posrges_init.sql: |-
    CREATE SCHEMA  ayoub;
    create table ayoub.campagne (
    	id_campagne bigserial not null,
    	id_planification int8 null,
    	id_job_instance int8 null,
    	denomination_expediteur varchar(255) null,
    	adresse_email_expediteur varchar(317) null,
    	constraint pk_campagne primary key (id_campagne)
    );

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-password
                  key: db-password
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - name: dbcreation-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: dbcreation-script
          configMap:
            name: dbcreation-script-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31080



