---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_USER: {{.Values.config.POSTGRES_USER}}
  POSTGRES_DB: {{.Values.config.POSTGRES_DB}}

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-password
type: Opaque
data:
  db-password: {{.Values.config.POSTGRES_PWD}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbcreation-script-configmap
data:
  posrges_init.sql: {{.Values.config.posrges_init_sql}}